openapi: 3.0.0
info:
  $ref: ./info/info.yaml
paths:
  $ref: ./paths/pathindex.yaml
components:
  schemas:
    $ref: ./schemas/index.yaml
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT